name: tutorconnect
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Localizations
  flutter_localizations:
    sdk: flutter

  # Cupertino Icons
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1

  # State management
  provider: ^6.1.5+1
  flutter_riverpod: ^2.6.1

  # InternacionalizaciÃ³n y formatos
  intl: ^0.20.2

  # Splash screen
  flutter_native_splash: ^2.4.6
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: 0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/login_banner.png
    - assets/images/app_banner.png
    - assets/images/app_icon.png # icono de la app

# ðŸ”¹ ConfiguraciÃ³n del splash screen
flutter_native_splash:
  color: "#910048" # color de fondo
  image: assets/images/app_icon.png # Imagen centrada (logo)
  android: true
  ios: true
  web: false

# ðŸ”¹ ConfiguraciÃ³n del icono de la app
flutter_icons:
  android: true
  ios: true
  web: false
  image_path: "assets/images/app_icon.png" # usado para iOS
  adaptive_icon_background: "#910048" # color de fondo para Android
  adaptive_icon_foreground: "assets/images/app_icon.png"
